I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 1213, in script
    if forgave_ioriel == True:
  File "game/script.rpy", line 1213, in <module>
    if forgave_ioriel == True:
NameError: name 'forgave_ioriel' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 1213, in script
    if forgave_ioriel == True:
  File "C:\Users\Eric\Downloads\renpy-7.0.0-sdk\renpy\ast.py", line 1729, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\Eric\Downloads\renpy-7.0.0-sdk\renpy\python.py", line 1943, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\Eric\Downloads\renpy-7.0.0-sdk\renpy\python.py", line 1936, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 1213, in <module>
    if forgave_ioriel == True:
NameError: name 'forgave_ioriel' is not defined

Windows-8-6.2.9200
Ren'Py 7.0.0.196
The Sun Still Rises 0.2a
Tue Jul 17 04:24:42 2018
